version: "{branch} {build}"

build:
  verbosity: detailed

build_script:
  - gradlew.bat assemble --info --no-daemon

test_script:
  - gradlew.bat test check gradleTest --info --no-daemon

branches:
  only:
    - master
    - development

environment:
  matrix:  
  - JAVA_HOME: C:\Program Files\Java\jdk1.8.0

cache:
  - C:\Users\appveyor\.gradle
